#ifndef __DEFINES__H__
#define __DEFINES__H__

#define MATRIX_EL_WEIGHT 3
#define MATRIX_SIZE_WEIGHT 2
#define MATRIX_ESTIMATE_WEIGHT 3
#define MATRIX_BORDER_WEIGHT 1
#define MATRIX_IS_INCLUDED_WEIGHT 1

#define ROOT_PID 0
#define LEFT_PID 1
#define RIGHT_PID 2
#define PARALLEL_PROC_COUNT 2

#endif